POST http://localhost:3000/api/sync
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1OTEzODQ2OCwiZXhwIjoxNzU5NzQzMjY4LCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.XpC_XxTBmu7a92Hb4GQTt79ZUy8h3P-_6AdRudYCbLw

{}

###
GET http://localhost:3000/api/stations?city=Kyiv&status=active&page=1&limit=10
Accept: application/json

###

###
GET http://localhost:3000/api/stations
Accept: application/json

###

###
GET http://localhost:3000/api/station/SAVEDNIPRO_001
Accept: application/json

###

###
POST http://localhost:3000/api/station
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1OTg1NTU1NiwiZXhwIjoxNzYwNDYwMzU2LCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.NKs5fWmJjTOG_8-H4xLeqjhPmw2FsS2_twkEF-ZMrTY

{
  "station_id": "CENTRAL_STATION1",
  "city_name": "Kyiv",
  "station_name": "Central Station",
  "local_name": "Центральна станція",
  "timezone": "Europe/Kiev",
  "geolocation": {
    "type": "Point",
    "coordinates": [30.5234, 50.4501]
  },
  "platform_name": "Platform A",
  "status": "active",
  "measured_parameters": ["PM10", "NO2"]
}

###

###
PUT http://localhost:3000/api/station/CENTRAL_STATION1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1OTg1NTU1NiwiZXhwIjoxNzYwNDYwMzU2LCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.NKs5fWmJjTOG_8-H4xLeqjhPmw2FsS2_twkEF-ZMrTY

{
  "city_name": "Kyiv3",
  "station_name": "Central Station",
  "local_name": "Центральна станція",
  "timezone": "Europe/Kiev",
  "geolocation": {
    "type": "Point",
    "coordinates": [30.5234, 50.4501]
  },
  "platform_name": "Platform A",
  "status": "active",
  "measured_parameters": ["PM10", "NO2"]
}

###

###
DELETE http://localhost:3000/api/station/CENTRAL_STATION1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1OTEzODQ2OCwiZXhwIjoxNzU5NzQzMjY4LCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.XpC_XxTBmu7a92Hb4GQTt79ZUy8h3P-_6AdRudYCbLw

###

###
GET http://localhost:3000/api/station/nearby/48.408/35.072/5000000
Accept: application/json
