POST http://localhost:3000/api/sync
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1ODk3NTY4MywiZXhwIjoxNzU4OTg1NzYzLCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.4k0I3T3T1xrt_6MP0yxHgsVboWLP4EuptYbLyjV4INo

{}

###
GET http://localhost:3000/api/stations?city=Kyiv&status=active&page=1&limit=10
Accept: application/json

###

###
GET http://localhost:3000/api/station/SAVEDNIPRO_001
Accept: application/json

###

###
POST http://localhost:3000/api/station
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1ODkwMTQxMiwiZXhwIjoxNzU4OTExNDkyLCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.DT5uYCFIWwXL80mJbdA6ooB5f_7AyFRy5tsz1XRih38

{
  "station_id": "CENTRAL_STATION1",
  "city_name": "Kyiv",
  "station_name": "Central Station",
  "local_name": "Центральна станція",
  "timezone": "Europe/Kiev",
  "geolocation": {
    "type": "Point",
    "coordinates": [30.5234, 50.4501]
  },
  "platform_name": "Platform A",
  "status": "active",
  "measured_parameters": ["PM10", "NO2"],
  "metadata": {
    "created_at": "2025-09-26T12:00:00.000Z",
    "updated_at": "2025-09-26T12:00:00.000Z",
    "data_source": "sensor_network",
    "last_measurement": "2025-09-26T12:00:00.000Z"
  }
}

###

###
PUT http://localhost:3000/api/station/CENTRAL_STATION1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1ODkwMTQxMiwiZXhwIjoxNzU4OTExNDkyLCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.DT5uYCFIWwXL80mJbdA6ooB5f_7AyFRy5tsz1XRih38

{
  "city_name": "Kyiv3",
  "station_name": "Central Station",
  "local_name": "Центральна станція",
  "timezone": "Europe/Kiev",
  "geolocation": {
    "type": "Point",
    "coordinates": [30.5234, 50.4501]
  },
  "platform_name": "Platform A",
  "status": "active",
  "measured_parameters": ["PM10", "NO2"],
  "metadata": {
    "created_at": "2025-09-26T12:00:00.000Z",
    "updated_at": "2025-09-26T12:00:00.000Z",
    "data_source": "sensor_network",
    "last_measurement": "2025-09-26T12:00:00.000Z"
  }
}

###

###
DELETE http://localhost:3000/api/station/CENTRAL_STATION1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QxMmYzNTY3NTF5NCIsInJvbGVzIjoidXNlcixhZG1pbiIsImlhdCI6MTc1ODkwMTQxMiwiZXhwIjoxNzU4OTExNDkyLCJzdWIiOiI2OGQ1NTA4NmU0ZDJhNDI2MmNiZGYwNGEifQ.DT5uYCFIWwXL80mJbdA6ooB5f_7AyFRy5tsz1XRih38

###

###
GET http://localhost:3000/api/station/nearby/48.408/35.072/5000000
Accept: application/json
